/* Simple Queries */
/* 17 - Show the name,sales,quota of employee number 105 */
/* SYNTAX - SELECT [COLUMN_NAME] FROM [TABLE_NAME] WHERE [COLUMN_NAME] = [COLUMN_DATA_FIELD]; */

/* ANSWER */ 
SELECT EMPL_NUM,NAME,SALES,QUOTA FROM SALESREPS WHERE EMPL_NUM='105';