/* Simple Queries */
/* 18 - Show the employees managed by Bob Smith (employee 104) */
/* SYNTAX - SELECT [COLUMN_NAME] FROM [TABLE_NAME] WHERE [COLUMN_NAME1] = [COLUMN_DATA_FIELD1] AND [COLUMN_NAME2] = [COLUMN_DATA_FIELD2]; */

/* ANSWER */ 
SELECT EMPL_NUM,NAME,REP_OFFICE FROM SALESREPS WHERE NAME='BOB SMITH' AND EMPL_NUM='104';